import mongoose from 'mongoose';
import dotenv from 'dotenv';

dotenv.config();

const sampleCompanies = [
  {
    name: 'TechVision Solutions',
    logo: 'https://via.placeholder.com/100x100/5FA8D3/ffffff?text=TV',
    industry: 'Information Technology',
    description: 'Leading provider of enterprise software solutions and digital transformation services. We help businesses modernize their operations with cutting-edge technology.',
    website: 'https://techvision.example.com',
    size: '501-1000',
    location: 'Bengaluru, Karnataka',
    founded: 2010,
    specialties: ['Cloud Computing', 'AI/ML', 'Enterprise Software', 'DevOps'],
    hiringFor: ['Software Engineers', 'Data Scientists', 'Project Managers'],
    activeJobs: 45,
    featured: true,
    isVerified: true
  },
  {
    name: 'HealthFirst Medical',
    logo: 'https://via.placeholder.com/100x100/10b981/ffffff?text=HF',
    industry: 'Healthcare',
    description: 'Comprehensive healthcare provider offering medical services, health insurance, and wellness programs across India.',
    website: 'https://healthfirst.example.com',
    size: '1000+',
    location: 'Mumbai, Maharashtra',
    founded: 2005,
    specialties: ['Healthcare Services', 'Medical Insurance', 'Telemedicine', 'Pharmacy'],
    hiringFor: ['Doctors', 'Nurses', 'Healthcare Administrators'],
    activeJobs: 32,
    featured: true,
    isVerified: true
  },
  {
    name: 'FinanceHub India',
    logo: 'https://via.placeholder.com/100x100/f59e0b/ffffff?text=FH',
    industry: 'Financial Services',
    description: 'Premier financial services company specializing in investment banking, wealth management, and fintech solutions.',
    website: 'https://financehub.example.com',
    size: '201-500',
    location: 'Mumbai, Maharashtra',
    founded: 2012,
    specialties: ['Investment Banking', 'Wealth Management', 'Fintech', 'Insurance'],
    hiringFor: ['Financial Analysts', 'Investment Bankers', 'Software Developers'],
    activeJobs: 28,
    featured: true,
    isVerified: true
  },
  {
    name: 'GreenEnergy Corp',
    logo: 'https://via.placeholder.com/100x100/22c55e/ffffff?text=GE',
    industry: 'Renewable Energy',
    description: 'Pioneering sustainable energy solutions including solar, wind, and hydroelectric power generation projects.',
    website: 'https://greenenergy.example.com',
    size: '51-200',
    location: 'Gurugram, Haryana',
    founded: 2018,
    specialties: ['Solar Energy', 'Wind Power', 'Energy Storage', 'Carbon Credits'],
    hiringFor: ['Engineers', 'Project Managers', 'Environmental Specialists'],
    activeJobs: 15,
    featured: false,
    isVerified: true
  },
  {
    name: 'RetailMax',
    logo: 'https://via.placeholder.com/100x100/ec4899/ffffff?text=RM',
    industry: 'Retail & E-commerce',
    description: 'Omnichannel retail company offering fashion, electronics, and home goods through physical stores and online platforms.',
    website: 'https://retailmax.example.com',
    size: '1000+',
    location: 'Delhi NCR',
    founded: 2008,
    specialties: ['E-commerce', 'Retail', 'Supply Chain', 'Customer Experience'],
    hiringFor: ['Sales Associates', 'Marketing', 'Logistics', 'IT'],
    activeJobs: 56,
    featured: true,
    isVerified: true
  },
  {
    name: 'EduLearn Platform',
    logo: 'https://via.placeholder.com/100x100/8b5cf6/ffffff?text=EL',
    industry: 'Education & EdTech',
    description: 'Innovative online learning platform offering courses, certifications, and degree programs in partnership with top universities.',
    website: 'https://edulearn.example.com',
    size: '201-500',
    location: 'Bengaluru, Karnataka',
    founded: 2015,
    specialties: ['Online Learning', 'Higher Education', 'Corporate Training', 'Skill Development'],
    hiringFor: ['Instructors', 'Content Developers', 'Marketing', 'Technology'],
    activeJobs: 22,
    featured: false,
    isVerified: true
  },
  {
    name: 'AutoDrive Motors',
    logo: 'https://via.placeholder.com/100x100/3b82f6/ffffff?text=AD',
    industry: 'Automotive',
    description: 'Electric and autonomous vehicle manufacturer committed to sustainable transportation solutions.',
    website: 'https://autodrive.example.com',
    size: '501-1000',
    location: 'Pune, Maharashtra',
    founded: 2016,
    specialties: ['Electric Vehicles', 'Autonomous Driving', 'Battery Technology', 'Smart Mobility'],
    hiringFor: ['Engineers', 'Designers', 'Quality Assurance', 'Manufacturing'],
    activeJobs: 38,
    featured: true,
    isVerified: true
  },
  {
    name: 'LogiPrime Logistics',
    logo: 'https://via.placeholder.com/100x100/f97316/ffffff?text=LP',
    industry: 'Logistics & Supply Chain',
    description: 'End-to-end logistics and supply chain management company offering warehousing, transportation, and inventory solutions.',
    website: 'https://logiprime.example.com',
    size: '501-1000',
    location: 'Hyderabad, Telangana',
    founded: 2011,
    specialties: ['Warehousing', 'Transportation', 'Last Mile Delivery', 'Inventory Management'],
    hiringFor: ['Operations', 'Drivers', 'Warehouse Staff', 'Technology'],
    activeJobs: 41,
    featured: false,
    isVerified: true
  },
  {
    name: 'MediaMax Entertainment',
    logo: 'https://via.placeholder.com/100x100/ef4444/ffffff?text=MM',
    industry: 'Media & Entertainment',
    description: 'Content creation and broadcasting company producing films, television shows, and digital content.',
    website: 'https://mediamax.example.com',
    size: '201-500',
    location: 'Mumbai, Maharashtra',
    founded: 2009,
    specialties: ['Film Production', 'Television', 'Digital Content', 'Music'],
    hiringFor: ['Creative Roles', 'Production', 'Marketing', 'Technology'],
    activeJobs: 18,
    featured: false,
    isVerified: true
  },
  {
    name: 'ConstructionPro',
    logo: 'https://via.placeholder.com/100x100/78716c/ffffff?text=CP',
    industry: 'Construction & Real Estate',
    description: 'Premier construction and real estate development company specializing in residential, commercial, and infrastructure projects.',
    website: 'https://constructionpro.example.com',
    size: '501-1000',
    location: 'Noida, Uttar Pradesh',
    founded: 2007,
    specialties: ['Commercial Construction', 'Residential Projects', 'Infrastructure', 'Interior Design'],
    hiringFor: ['Engineers', 'Project Managers', 'Architects', 'Sales'],
    activeJobs: 25,
    featured: true,
    isVerified: true
  },
  {
    name: 'FoodieHub',
    logo: 'https://via.placeholder.com/100x100/14b8a6/ffffff?text=FH',
    industry: 'Food & Beverage',
    description: 'Fast-growing food delivery and restaurant aggregation platform connecting diners with the best local cuisines.',
    website: 'https://foodiehub.example.com',
    size: '501-1000',
    location: 'Gurugram, Haryana',
    founded: 2017,
    specialties: ['Food Delivery', 'Restaurant Partner', 'Cloud Kitchen', 'Grocery'],
    hiringFor: ['Delivery Partners', 'Marketing', 'Technology', 'Operations'],
    activeJobs: 35,
    featured: false,
    isVerified: true
  },
  {
    name: 'CyberShield Security',
    logo: 'https://via.placeholder.com/100x100/64748b/ffffff?text=CS',
    industry: 'Cybersecurity',
    description: 'Advanced cybersecurity solutions provider offering threat detection, penetration testing, and security consulting services.',
    website: 'https://cybershield.example.com',
    size: '51-200',
    location: 'Pune, Maharashtra',
    founded: 2019,
    specialties: ['Threat Detection', 'Penetration Testing', 'Security Audit', 'Incident Response'],
    hiringFor: ['Security Analysts', 'Ethical Hackers', 'Consultants'],
    activeJobs: 12,
    featured: false,
    isVerified: true
  },
  {
    name: 'CloudNine Technologies',
    logo: 'https://via.placeholder.com/100x100/0ea5e9/ffffff?text=CN',
    industry: 'Information Technology',
    description: 'Cloud infrastructure and DevOps services company helping enterprises migrate and manage cloud workloads efficiently.',
    website: 'https://cloudnine.example.com',
    size: '201-500',
    location: 'Hyderabad, Telangana',
    founded: 2014,
    specialties: ['Cloud Migration', 'DevOps', 'AWS', 'Azure', 'Kubernetes'],
    hiringFor: ['Cloud Engineers', 'DevOps Engineers', 'Solutions Architects'],
    activeJobs: 28,
    featured: true,
    isVerified: true
  },
  {
    name: 'PharmaCare Labs',
    logo: 'https://via.placeholder.com/100x100/22c55e/ffffff?text=PC',
    industry: 'Pharmaceuticals',
    description: 'Research-driven pharmaceutical company developing innovative medicines and healthcare solutions for a healthier tomorrow.',
    website: 'https://pharmacare.example.com',
    size: '1000+',
    location: 'Ahmedabad, Gujarat',
    founded: 2003,
    specialties: ['Drug Research', 'Clinical Trials', 'Manufacturing', 'Quality Assurance'],
    hiringFor: ['Researchers', 'Pharmacists', 'Quality Control', 'Sales'],
    activeJobs: 55,
    featured: true,
    isVerified: true
  },
  {
    name: 'BankSecure Finance',
    logo: 'https://via.placeholder.com/100x100/1e40af/ffffff?text=BS',
    industry: 'Banking & Financial Services',
    description: 'Digital banking and fintech company providing secure online banking, loans, and investment solutions.',
    website: 'https://banksecure.example.com',
    size: '501-1000',
    location: 'Mumbai, Maharashtra',
    founded: 2015,
    specialties: ['Digital Banking', 'Lending', 'Payments', 'Wealth Management'],
    hiringFor: ['Software Developers', 'Bankers', 'Compliance Officers', 'Analysts'],
    activeJobs: 42,
    featured: false,
    isVerified: true
  },
  {
    name: 'EduSpark Academy',
    logo: 'https://via.placeholder.com/100x100/a855f7/ffffff?text=ES',
    industry: 'Education & EdTech',
    description: 'Interactive learning platform offering coding bootcamps, professional courses, and career counseling services.',
    website: 'https://eduspark.example.com',
    size: '51-200',
    location: 'Bengaluru, Karnataka',
    founded: 2020,
    specialties: ['Coding Bootcamps', 'Professional Courses', 'Career Counseling', 'Skill Development'],
    hiringFor: ['Instructors', 'Content Creators', 'Marketing', 'Tech Team'],
    activeJobs: 15,
    featured: false,
    isVerified: true
  },
  {
    name: 'GreenLeaf Agriculture',
    logo: 'https://via.placeholder.com/100x100/16a34a/ffffff?text=GL',
    industry: 'Agriculture & AgTech',
    description: 'Sustainable agriculture company using technology to improve farming practices and connect farmers with markets.',
    website: 'https://greenleaf.example.com',
    size: '201-500',
    location: 'Pune, Maharashtra',
    founded: 2016,
    specialties: ['Smart Farming', 'Organic Products', 'Supply Chain', 'Agricultural Technology'],
    hiringFor: ['Agronomists', 'Engineers', 'Operations', 'Sales'],
    activeJobs: 20,
    featured: false,
    isVerified: true
  },
  {
    name: 'TravelEase Holidays',
    logo: 'https://via.placeholder.com/100x100/f43f5e/ffffff?text=TE',
    industry: 'Travel & Tourism',
    description: 'Full-service travel agency offering personalized vacation packages, corporate travel, and destination management.',
    website: 'https://travelease.example.com',
    size: '201-500',
    location: 'Jaipur, Rajasthan',
    founded: 2012,
    specialties: ['Vacation Packages', 'Corporate Travel', 'Visa Services', 'Hotel Bookings'],
    hiringFor: ['Travel Consultants', 'Tour Guides', 'Marketing', 'Operations'],
    activeJobs: 18,
    featured: false,
    isVerified: true
  },
  {
    name: 'FitLife Sports',
    logo: 'https://via.placeholder.com/100x100/f97316/ffffff?text=FL',
    industry: 'Sports & Fitness',
    description: 'Premium fitness chain offering gym memberships, personal training, and sports nutrition products.',
    website: 'https://fitlife.example.com',
    size: '501-1000',
    location: 'Delhi NCR',
    founded: 2010,
    specialties: ['Fitness Centers', 'Personal Training', 'Sports Nutrition', 'Wellness Programs'],
    hiringFor: ['Fitness Trainers', 'Nutritionists', 'Sales', 'Operations'],
    activeJobs: 33,
    featured: false,
    isVerified: true
  },
  {
    name: 'LegalEase Advocates',
    logo: 'https://via.placeholder.com/100x100/6366f1/ffffff?text=LE',
    industry: 'Legal Services',
    description: 'Full-service law firm providing corporate legal advice, litigation support, and compliance consulting.',
    website: 'https://legalease.example.com',
    size: '51-200',
    location: 'Mumbai, Maharashtra',
    founded: 2008,
    specialties: ['Corporate Law', 'Litigation', 'Compliance', 'Intellectual Property'],
    hiringFor: ['Lawyers', 'Paralegals', 'Legal Analysts', 'Compliance Officers'],
    activeJobs: 10,
    featured: false,
    isVerified: true
  },
  {
    name: 'SmartHome Solutions',
    logo: 'https://via.placeholder.com/100x100/8b5cf6/ffffff?text=SH',
    industry: 'Internet of Things (IoT)',
    description: 'Smart home automation company developing IoT devices, home security systems, and intelligent living solutions.',
    website: 'https://smarthome.example.com',
    size: '51-200',
    location: 'Bengaluru, Karnataka',
    founded: 2018,
    specialties: ['Home Automation', 'IoT Devices', 'Security Systems', 'Voice Assistants'],
    hiringFor: ['IoT Engineers', 'Hardware Designers', 'Software Developers', 'Designers'],
    activeJobs: 22,
    featured: true,
    isVerified: true
  },
  {
    name: 'FashionForward Retail',
    logo: 'https://via.placeholder.com/100x100/ec4899/ffffff?text=FF',
    industry: 'Fashion & Apparel',
    description: 'Trendy fashion brand designing and retailing contemporary clothing, accessories, and footwear.',
    website: 'https://fashionforward.example.com',
    size: '501-1000',
    location: 'Mumbai, Maharashtra',
    founded: 2013,
    specialties: ['Fashion Design', 'E-commerce', 'Retail', 'Supply Chain'],
    hiringFor: ['Designers', 'Merchandisers', 'E-commerce', 'Store Managers'],
    activeJobs: 40,
    featured: false,
    isVerified: true
  },
  {
    name: 'DataDriven Analytics',
    logo: 'https://via.placeholder.com/100x100/06b6d4/ffffff?text=DD',
    industry: 'Data Analytics & Big Data',
    description: 'Business intelligence company providing data analytics, machine learning, and predictive modeling solutions.',
    website: 'https://datadriven.example.com',
    size: '201-500',
    location: 'Bengaluru, Karnataka',
    founded: 2017,
    specialties: ['Business Intelligence', 'Machine Learning', 'Data Visualization', 'Predictive Analytics'],
    hiringFor: ['Data Scientists', 'ML Engineers', 'Data Analysts', 'BI Developers'],
    activeJobs: 35,
    featured: true,
    isVerified: true
  },
  {
    name: 'EcoBuild Constructions',
    logo: 'https://via.placeholder.com/100x100/84cc16/ffffff?text=EB',
    industry: 'Construction & Real Estate',
    description: 'Sustainable construction company focusing on green buildings, eco-friendly materials, and renewable energy integration.',
    website: 'https://ecobuild.example.com',
    size: '201-500',
    location: 'Chennai, Tamil Nadu',
    founded: 2014,
    specialties: ['Green Buildings', 'Sustainable Design', 'Renewable Energy', 'Infrastructure'],
    hiringFor: ['Civil Engineers', 'Architects', 'Project Managers', 'Safety Officers'],
    activeJobs: 28,
    featured: false,
    isVerified: true
  },
  {
    name: 'MediCare Plus',
    logo: 'https://via.placeholder.com/100x100/ef4444/ffffff?text=MC',
    industry: 'Healthcare',
    description: 'Multi-specialty hospital chain offering comprehensive medical care, emergency services, and diagnostic facilities.',
    website: 'https://medicareplus.example.com',
    size: '1000+',
    location: 'Hyderabad, Telangana',
    founded: 2000,
    specialties: ['Multi-specialty Care', 'Emergency Services', 'Diagnostics', 'Telemedicine'],
    hiringFor: ['Doctors', 'Nurses', 'Technicians', 'Administrators'],
    activeJobs: 75,
    featured: true,
    isVerified: true
  },
  {
    name: 'GameSphere Studios',
    logo: 'https://via.placeholder.com/100x100/7c3aed/ffffff?text=GS',
    industry: 'Gaming & Entertainment',
    description: 'Mobile and PC game development studio creating engaging games, AR/VR experiences, and interactive content.',
    website: 'https://gamesphere.example.com',
    size: '51-200',
    location: 'Pune, Maharashtra',
    founded: 2019,
    specialties: ['Game Development', 'AR/VR', 'Unity/Unreal', 'Game Design'],
    hiringFor: ['Game Developers', 'Artists', 'Game Designers', 'QA Testers'],
    activeJobs: 16,
    featured: false,
    isVerified: true
  },
  {
    name: 'TalentFirst HR',
    logo: 'https://via.placeholder.com/100x100/fbbf24/ffffff?text=TF',
    industry: 'Human Resources',
    description: 'HR consulting firm offering recruitment Process outsourcing, background verification, and HRIS solutions.',
    website: 'https://talentfirst.example.com',
    size: '201-500',
    location: 'Gurugram, Haryana',
    founded: 2011,
    specialties: ['RPO', 'Background Verification', 'HRIS', 'Payroll Processing'],
    hiringFor: ['Recruiters', 'HR Consultants', 'Payroll Specialists', 'Tech Team'],
    activeJobs: 30,
    featured: true,
    isVerified: true
  }
];

async function seed() {
  try {
    await mongoose.connect(process.env.MONGODB_URI);
    console.log('Connected to MongoDB');
    
    const Company = (await import('./models/Company.js')).default;
    
    await Company.deleteMany({});
    await Company.insertMany(sampleCompanies);
    
    console.log(`Successfully seeded ${sampleCompanies.length} companies!`);
    process.exit(0);
  } catch (error) {
    console.error('Error seeding companies:', error);
    process.exit(1);
  }
}

seed();
